# Generated by Django 5.1.3 on 2025-12-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='utr_number',
            field=models.CharField(blank=True, help_text='Bank UTR / transaction reference number', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='paid',
            field=models.BooleanField(default=False, help_text='Set to True after verifying payment manually'),
        ),
    ]
