# Generated by Django 5.1.3 on 2025-12-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_registration_utr_number_alter_registration_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='runner',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
